version: "3.8"

services:
  db:
    image: postgres:10-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    image: orcbat/backend:v1.0
    container_name: backend  
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
  frontend:
    image: orcbat/frontend:v1.0
    container_name: frontend
    ports:
      - "3000:3000"
volumes:
  db-data:
  
