version: '3.7'

services:
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8080:8080'
  frontend:
    container_name: frontend
    build: ../m347frontend/
    ports:
      - '3000:3000'
  db:
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
   
